version: "3.3"
services:
  rabbitmq:
    image: rabbitmq
    env_file: envs/rabbitmq.env

  postgres-db:
    image: postgres
    env_file: envs/db.env
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - "5432:5432"

  web:
    build: .
    image: edonssfall/yutvdom
    links:
      - postgres-db:db
      - rabbitmq:rabbitmq
    volumes:
      - .:/yutvdom_django
      - ./static:/static
    env_file:
      - envs/.env
      - envs/db.env
      - envs/rabbitmq.env
    command: "bin/bash -c 'pip install -r requirements.txt; invoke run'"

  celery:
    build: .
    image: edonssfall/yutvdom
    links:
      - postgres-db:db
      - rabbitmq:rabbitmq
    volumes:
      - .:/yutvdom_django
    env_file:
      - envs/.env
      - envs/db.env
      - envs/rabbitmq.env
    command: "celery -A config.celery.app worker"

  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static:ro
    links:
      - web:web
    ports:
      - 80:80

volumes:
  pgdata: {}
  static: {}
  