version: "3.3"
services:
  postgres-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=dreamer123
      - PGDATA=/var/lib/postgresql/pgdata/
      - POSTGRES_DB=yutvdom_db
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - "5432:5432"

  web:
    build: .
    image: edonssfall/yutvdom
    links:
      - postgres-db:db
    volumes:
      - .:/yutvdom_django
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    ports:
      - "8000:8000"

volumes:
  pgdata: {}