version: "3.3"
services:
  rabbitmq:
    image: rabbitmq
    env_file: envs/rabbitmq.env

  postgres-db:
    image: postgres
    env_file: envs/db.env
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - 5432:5432

  web:
    build: .
    image: edonssfall/yutvdom
    links:
      - postgres-db:db
      - rabbitmq:rabbitmq
    volumes:
      - .:/yutvdom_django
      - ./static:/static
    env_file:
      - envs/.env
      - envs/db.env
      - envs/rabbitmq.env
    ports:
      - 8000:8000

  celery:
    build: .
    image: edonssfall/yutvdom
    links:
      - postgres-db:db
      - rabbitmq:rabbitmq
    volumes:
      - .:/yutvdom_django
    env_file:
      - envs/.env
      - envs/db.env
      - envs/rabbitmq.env
    command: 'celery -A config.celery.app worker'


volumes:
  pgdata: {}
  static: {}
